"""create initial schema

Revision ID: 5e39c2ff8013
Revises: 
Create Date: 2026-04-21 03:11:36.818047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e39c2ff8013'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('ratings_count', sa.Integer(), nullable=False),
    sa.Column('isbn13', sa.String(length=20), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('origin_type', sa.String(length=30), nullable=False),
    sa.Column('source_platform', sa.String(length=30), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('translation_status', sa.String(length=20), nullable=False),
    sa.Column('creation_disclosure', sa.String(length=20), nullable=False),
    sa.Column('disclosure_source', sa.String(length=30), nullable=True),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_creation_disclosure'), 'books', ['creation_disclosure'], unique=False)
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    op.create_index(op.f('ix_books_language_code'), 'books', ['language_code'], unique=False)
    op.create_index(op.f('ix_books_moderation_status'), 'books', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_books_origin_type'), 'books', ['origin_type'], unique=False)
    op.create_index(op.f('ix_books_original_language'), 'books', ['original_language'], unique=False)
    op.create_index(op.f('ix_books_source'), 'books', ['source'], unique=False)
    op.create_index(op.f('ix_books_source_platform'), 'books', ['source_platform'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_translation_status'), 'books', ['translation_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_range'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_translation_status'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_source_platform'), table_name='books')
    op.drop_index(op.f('ix_books_source'), table_name='books')
    op.drop_index(op.f('ix_books_original_language'), table_name='books')
    op.drop_index(op.f('ix_books_origin_type'), table_name='books')
    op.drop_index(op.f('ix_books_moderation_status'), table_name='books')
    op.drop_index(op.f('ix_books_language_code'), table_name='books')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_index(op.f('ix_books_creation_disclosure'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
